### ISSUE TITLE
Can't close CMP on Samsung Tablet with Samsung Browser

### ISSUE THREAD

**Issue by AitorRodriguez990** [SUI-Components/adevinta-spain-components#128]
Hi 👋 

Sunday I tried Fotocasa on a Samsung Tablet, using Samsung Browser, and I was not able to close the CMP.

Here is the proof:

![ezgif com-resize](https://user-images.githubusercontent.com/13108014/65574675-5eb7a100-df6e-11e9-9a84-e603e7e4002f.gif)

**Comment by jordevo** [comment]
`404: image not found` 🤷‍♂️

**Comment by AitorRodriguez990** [comment]
Fixed! @jordevo
